### ISSUE TITLE
Inference on my own dataset

### ISSUE THREAD

**Issue by YoushaaMurhij** [yizhou-wang/RODNet#38]
Nice work, I wonder how to run RODNet on my own raw radar data (inference mode). Is it correct that I need first to generate [confmap](https://github.com/yizhou-wang/RODNet/blob/969cad6f08b8957b26bc16f86ac4e835d1294050/rodnet/core/confidence_map/generate.py#L7) for the raw data without the classes of the objects? 

Thanks!

**Comment by yizhou-wang** [comment]
For inference on your own data, you should generate RF images (range-angle heatmaps) with a similar format in our CRUW dataset. ConfMap is not needed for inference. It is only used during the training. 

However, inference without any training on your own data may lead to a bad result because the RF images might be very different with different radar hardware and configurations.

**Comment by YoushaaMurhij** [comment]
Yeah. Sorry, I meant the RF images. I got it.
Thanks for your answer!
